useNodeVersion: 24.4.1

packages:
  - packages/*

onlyBuiltDependencies:
  - core-js

catalog:
  "@biomejs/biome": "2.0.6"
  "@rsbuild/core": "^1.4.3"
  "typescript": "^5.8.3"
  "@types/node": "^24.0.14"
